"""adicionando o amd

Revision ID: 1c68ff56c262
Revises: 86b09f9477c8
Create Date: 2026-05-16 17:19:02.815419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c68ff56c262'
down_revision: Union[str, Sequence[str], None] = '86b09f9477c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('adiminstrador', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'adiminstrador')
    # ### end Alembic commands ###
