"""removendo o adm

Revision ID: 86b09f9477c8
Revises: cb10dda92595
Create Date: 2026-05-16 17:16:28.686652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b09f9477c8'
down_revision: Union[str, Sequence[str], None] = 'cb10dda92595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'adiminstrador')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('adiminstrador', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
